---
- name: Reload PostgreSQL
  service: name=postgresql state=reloaded
  ignore_errors: True

- name: Start PostgreSQL
  service: name=postgresql state=started
  ignore_errors: True
 
 
- name: Restart PostgreSQL
  service: name=postgresql state=started
#   debug: 
#     msg: "Restarting Postgresql"
  ignore_errors: True
